"""add users and user_id links

Revision ID: b19331843678
Revises: ed61573e26d2
Create Date: 2026-07-19 16:28:36.754862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19331843678'
down_revision: Union[str, Sequence[str], None] = 'ed61573e26d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.add_column('bookings', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_foreign_key('fk_bookings_user_id', 'bookings', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('conversations', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_foreign_key('fk_conversations_user_id', 'conversations', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('payments', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_foreign_key('fk_payments_user_id', 'payments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('trips', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_foreign_key('fk_trips_user_id', 'trips', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_trips_user_id', 'trips', type_='foreignkey')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_column('trips', 'user_id')
    op.drop_constraint('fk_payments_user_id', 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_column('payments', 'user_id')
    op.drop_constraint('fk_conversations_user_id', 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_column('conversations', 'user_id')
    op.drop_constraint('fk_bookings_user_id', 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_column('bookings', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
