"""add message seq column

Revision ID: ed61573e26d2
Revises: c48a01e88aff
Create Date: 2026-07-19 11:40:59.210949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed61573e26d2'
down_revision: Union[str, Sequence[str], None] = 'c48a01e88aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'seq')
    # ### end Alembic commands ###
